use_frameworks!

platform :ios, '10.0'

target 'ClipdropAIPod_Example' do
  pod 'ClipdropAIPod', :path => '../'

  target 'ClipdropAIPod_Tests' do
    inherit! :search_paths
pod 'Alamofire', '~> 5.9.1'
    
  end
end
